// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tBy8c4Bj2taXsl9L6A7mqKQbuuVQGQM',
    appId: '1:561128399734:web:aa0bd33e60413dfd1e5057',
    messagingSenderId: '561128399734',
    projectId: 'easytravel-a2ae0',
    authDomain: 'easytravel-a2ae0.firebaseapp.com',
    storageBucket: 'easytravel-a2ae0.firebasestorage.app',
    measurementId: 'G-3MKGYXKWCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDug6p8b-Ofq1wxxdbB0LdGQ9KfnIvPb9M',
    appId: '1:561128399734:android:c4719372ad6ccd031e5057',
    messagingSenderId: '561128399734',
    projectId: 'easytravel-a2ae0',
    storageBucket: 'easytravel-a2ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkKf77fyx_ZEjoy-JazNFAm2EpiKV9Fw',
    appId: '1:561128399734:ios:d1589aed9665792b1e5057',
    messagingSenderId: '561128399734',
    projectId: 'easytravel-a2ae0',
    storageBucket: 'easytravel-a2ae0.firebasestorage.app',
    iosBundleId: 'com.example.easytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCkKf77fyx_ZEjoy-JazNFAm2EpiKV9Fw',
    appId: '1:561128399734:ios:d1589aed9665792b1e5057',
    messagingSenderId: '561128399734',
    projectId: 'easytravel-a2ae0',
    storageBucket: 'easytravel-a2ae0.firebasestorage.app',
    iosBundleId: 'com.example.easytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7tBy8c4Bj2taXsl9L6A7mqKQbuuVQGQM',
    appId: '1:561128399734:web:4ffcbc1fde1039941e5057',
    messagingSenderId: '561128399734',
    projectId: 'easytravel-a2ae0',
    authDomain: 'easytravel-a2ae0.firebaseapp.com',
    storageBucket: 'easytravel-a2ae0.firebasestorage.app',
    measurementId: 'G-F97WVRER0J',
  );
}
